---
apiVersion: v1
kind: Namespace
metadata:
  name: pending-pod-error-simulator
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-allocation
  namespace: pending-pod-error-simulator
spec:
  hard:
    requests.cpu: 1000m
    requests.memory: "100Mi"
    limits.cpu: 2000m
    limits.memory: "200Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pending-pod-deployment
  namespace: pending-pod-error-simulator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pending-app
  template:
    metadata:
      labels:
        app: pending-app
    spec:
      nodeSelector:
        disktype: ssd
      containers:
        - name: from-my-docker-hub
          image: olaab/localubuntu-server-container:v1.0
          command: ["/bin/sh"]
          args: ["-c", "sleep 3 && nginx -g 'daemon off;'"]
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 200m
              memory: 10Mi
            limits:
              cpu: 400m
              memory: 20Mi
          startupProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: pending-pod-service
  namespace: pending-pod-error-simulator
spec:
  type: NodePort
  selector:
    app: pending-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
